import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class VCamApp {
    private JPanel mainPanel;
    private JLabel imageLabel;

    //
    private int counter = 0;
    ImageIcon[] images = {
            new ImageIcon("./cat1.jpg"),
            new ImageIcon("./cat2.jpg")
    };

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        imageLabel = new JLabel();
        imageLabel.setText("Label");
        mainPanel.add(imageLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }


    private void initComponents() {
        for (ImageIcon image: images) {

        }
        Timer timer = new Timer(1000, (ActionEvent ae) -> {
            imageLabel.setIcon(images[counter]);
            if (counter >= images.length - 1) {
                counter = 0;
            } else {
                counter++;
            }
        });
        timer.setInitialDelay(0);
        timer.start();
    }

    public VCamApp() {
        System.out.println("VcamApp constructor called");
        initComponents();
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("VCamApp");
        VCamApp vcamApp = new VCamApp();
        frame.setContentPane(vcamApp.mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

}
